[package]
name = "bb8-tiberius"
version = "0.15.0"
authors = ["Jacob Brown <kardeiz@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "bb8 connection manager for Tiberius"
repository = "https://github.com/kardeiz/bb8-tiberius"
keywords = ["mssql", "tiberius", "database", "pool"]

[dependencies]
tiberius = { version = "0.12", default-features = false }
bb8 = "0.8"
thiserror = "1.0.23"
tokio = { version = "1.1.0", features = ["net"], optional = true }
tokio-util = { version = "0.7", features = ["compat"], optional = true }
async-trait = "0.1.42"
async-std = { version = "1.9.0", optional = true }
tracing = "0.1"

[features]
default = ["chrono",  "tds73", "with-tokio", "sql-browser", "tiberius/winauth"]
tls = ["tiberius/rustls"]
with-tokio = ["tokio", "tokio-util"]
with-async-std = ["async-std"]
tds73 = ["tiberius/tds73"]
chrono = ["tiberius/chrono"]
sql-browser = ["tiberius/sql-browser-tokio"]

[dev-dependencies]
tokio = { version = "1.1.0", features = ["macros", "rt-multi-thread"] }
